# Generated by Django 4.2.3 on 2023-07-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Коментарии'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(max_length=255, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='subtitle',
            field=models.CharField(default='Подзаголовок', max_length=255, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default='Название', max_length=255, verbose_name='Название новости'),
        ),
    ]
