# Generated by Django 4.2.3 on 2023-07-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_gallery_category_delete_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='created_at_ru',
            field=models.DateTimeField(null=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='news',
            name='created_at_uz',
            field=models.DateTimeField(null=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='news',
            name='subtitle_ru',
            field=models.TextField(default='Подзаголовок', null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='subtitle_uz',
            field=models.TextField(default='Подзаголовок', null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(default='Название', max_length=255, null=True, verbose_name='Название новости'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(default='Название', max_length=255, null=True, verbose_name='Название новости'),
        ),
    ]
