# Generated by Django 4.2.3 on 2023-07-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_news_created_at_ru_news_created_at_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='created_at_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='created_at_uz',
        ),
        migrations.AddField(
            model_name='news',
            name='subtitle_en',
            field=models.TextField(default='Подзаголовок', null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(default='Название', max_length=255, null=True, verbose_name='Название новости'),
        ),
    ]
